/** The shared catalogue, generated by `bun run build:catalog` into `data/catalog.json`. */
import catalog from "../../../data/catalog.json";
import type { CaseDto, SetDto } from "../../shared/types";

export const sets = catalog.sets as SetDto[];
export const cases = catalog.cases as CaseDto[];
