import {afterEach,expect,test} from "bun:test";
import {adminToken,createRustApi,openDb} from "./backend";
import {createApiClient} from "../src/client/api-client";
const cleanup:(()=>void)[]=[];afterEach(()=>cleanup.splice(0).forEach(fn=>fn()));
/** The token generated by the latest `setup`, used by `login` unless another is given. */
let currentToken="";
function setup(settings:Record<string,string>={},{token=true}={}) {
 const db=openDb();cleanup.push(()=>db.db.close());const app=createRustApi(db.path,settings);
 // Generated while the server runs, as on the Pi.
 if(token)currentToken=adminToken(db.path);
 return {db,app,origin:`http://127.0.0.1:${app.server.port}`,token:currentToken};
}
async function login(origin:string,token=currentToken,headers:Record<string,string>={}) {const response=await fetch(origin+"/api/admin/login",{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify({token})});const value=await response.json();return {response,value,cookie:response.headers.get("set-cookie")?.split(";")[0]??""};}

test("admin access requires the container-generated token; HttpOnly session lasts one day, survives restart, and can be revoked",async()=>{
 const {origin,db,app}=setup();
 expect((await fetch(origin+"/api/admin/overview")).status).toBe(401);
 const user=await createApiClient(origin,{getToken:()=>null}).register("ordinary_user","a-long-test-password");
 expect((await fetch(origin+"/api/admin/overview",{headers:{authorization:"Bearer "+user.token}})).status).toBe(401);
 expect((await login(origin,"cbx_admin_"+"0".repeat(64))).response.status).toBe(401);expect((await login(origin,"")).response.status).toBe(422);
 const admin=await login(origin);expect(admin.response.status).toBe(200);
 const header=admin.response.headers.get("set-cookie")!;expect(header).toContain("HttpOnly");expect(header).toContain("SameSite=Strict");expect(header).toContain("Max-Age=86400");
 expect(admin.value.expiresAt-Date.now()).toBeGreaterThan(86390000);expect(admin.value.expiresAt-Date.now()).toBeLessThanOrEqual(86400000);
 const stored=db.db.query<{token_hash:string}>("SELECT token_hash FROM admin_tokens").get()!;expect(admin.cookie).not.toContain(stored.token_hash);
 app.server.stop();const restarted=createRustApi(db.path);const again=`http://127.0.0.1:${restarted.server.port}`;
 expect((await fetch(again+"/api/admin/overview",{headers:{cookie:admin.cookie}})).status).toBe(200);
 expect((await fetch(again+"/api/admin/logout",{method:"POST",headers:{cookie:admin.cookie}})).status).toBe(200);
 expect((await fetch(again+"/api/admin/overview",{headers:{cookie:admin.cookie}})).status).toBe(401);
 const expired=await login(again);db.db.exec("UPDATE admin_tokens SET expires_at=0");expect((await fetch(again+"/api/admin/overview",{headers:{cookie:expired.cookie}})).status).toBe(401);
});

test("admin lists accounts and HTTP traffic without secrets or spoofed IPs",async()=>{
 const {origin,db}=setup();const remote=createApiClient(origin,{getToken:()=>null});await remote.register("visible_user","a-long-test-password");
 // Guests can no longer be created; one left from before still shows as such.
 db.db.exec("INSERT INTO users(id,username) VALUES('old-guest','guest-old')");
 await fetch(origin+"/missing-path?token=do-not-log-this",{headers:{"x-forwarded-for":"203.0.113.200",authorization:"Bearer do-not-log-this"}});
 const admin=await login(origin);
 const users=await adminGet(origin,admin.cookie,"/api/admin/users?filter=registered");
 expect(users.counts).toEqual({all:2,registered:1,guests:1});expect(users.rows.map((r:any)=>r.username)).toEqual(["visible_user"]);
 expect((await adminGet(origin,admin.cookie,"/api/admin/users")).rows).toHaveLength(2);
 const requests=await adminGet(origin,admin.cookie,"/api/admin/requests?limit=200");
 const row=requests.rows.find((r:any)=>r.path==="/missing-path");expect(row.status).toBe(404);expect(row.ip).toBe("127.0.0.1");
 const ips=await adminGet(origin,admin.cookie,"/api/admin/ips");expect(ips.rows.map((r:any)=>r.ip)).toEqual(["127.0.0.1"]);expect(ips.rows[0].requests).toBeGreaterThan(2);
 const everything=JSON.stringify([users,requests,ips]);for(const secret of ["do-not-log-this","password_hash","token_hash"])expect(everything).not.toContain(secret);
 expect((await fetch(origin+"/aaaaadmin")).status).toBe(404);
});

test("per-IP rate limits return 429 with Retry-After and cannot be bypassed by spoofing forwarding headers",async()=>{
 const {origin}=setup({CUBIX_RATE_LIMIT:"5"});const responses=[];
 for(let i=0;i<7;i++)responses.push(await fetch(origin+"/api/health",{headers:{"x-forwarded-for":`192.0.2.${i}`}}));
 expect(responses.filter(r=>r.status===429).length).toBeGreaterThanOrEqual(3);expect(responses.at(-1)!.headers.get("retry-after")).toBe("60");
});

test("health probes are excluded from admin logs, counters and IP listings even when rate limited",async()=>{
 const {origin}=setup({CUBIX_TRUSTED_PROXIES:"127.0.0.1",CUBIX_RATE_LIMIT:"5"});
 for(let i=0;i<7;i++){
  const response=await fetch(origin+"/api/health?probe=1",{headers:{"x-forwarded-for":"203.0.113.8"}});
  expect(response.status).toBe(i<5?200:429);
  expect(response.headers.get("x-content-type-options")).toBe("nosniff");
 }
 // The admin's own IP shares the limit of 5: the start-up health probe, the login and three reads.
 const admin=await login(origin);
 const requests=await adminGet(origin,admin.cookie,"/api/admin/requests?limit=200");
 expect(requests.total).toBe(1);expect(requests.rows.map((r:any)=>r.path)).toEqual(["/api/admin/login"]);
 const overview=await adminGet(origin,admin.cookie,"/api/admin/overview");
 expect(overview.requests).toMatchObject({errorsToday:0,rateLimitedToday:0});expect(overview.ips).toEqual({today:1,d7:1,d30:1,live:1});
 const filtered=await adminGet(origin,admin.cookie,"/api/admin/ips?q=203.0.113.8");expect(filtered.total).toBe(0);expect(filtered.rows).toHaveLength(0);
});

test("admin login has a separate brute-force limit and rejects cross-origin submissions",async()=>{
 const {origin}=setup();const cross=await login(origin,undefined,{origin:"https://foreign.example"});expect(cross.response.status).toBe(403);
 for(let i=0;i<4;i++)expect((await login(origin,"wrong-token")).response.status).toBe(401);
 const limited=await login(origin);expect(limited.response.status).toBe(429);expect(limited.response.headers.get("retry-after")).toBe("180");
});

test("only configured proxies may supply client IPs; the rightmost untrusted hop wins",async()=>{
 const {origin}=setup({CUBIX_TRUSTED_PROXIES:"127.0.0.1"});
 await fetch(origin+"/api/moves",{headers:{"x-forwarded-for":"192.0.2.5, 203.0.113.7"}});
 const admin=await login(origin);const body=await adminGet(origin,admin.cookie,"/api/admin/ips?q=203.0.113.7");
 expect(body.rows).toMatchObject([{ip:"203.0.113.7",requests:1}]);
 expect((await adminGet(origin,admin.cookie,"/api/admin/ips?q=192.0.2.5")).total).toBe(0);
});

test("without a generated token administration is disabled, whatever CUBIX_ADMIN_PASSWORD says",async()=>{
 const {origin,db}=setup({},{token:false});
 const disabled=await login(origin,"synthetic-admin-test-password");expect(disabled.response.status).toBe(503);
 expect(disabled.value.error).toBe("Run `cubix-api admin-token` in the container to enable administration");
 expect((await fetch(origin+"/api/admin/overview")).status).toBe(503);
 const token=adminToken(db.path);expect(token).toMatch(/^cbx_admin_[0-9a-f]{64}$/);
 expect((await login(origin,"synthetic-admin-test-password")).response.status).toBe(401);
 expect((await login(origin,token)).response.status).toBe(200);
 // The upload password needs no token; the token opens no upload.
 const upload=(password:string)=>fetch(origin+"/api/mobile/updates",{method:"PUT",headers:{authorization:"Bearer "+password,"content-type":"application/json"},body:"{}"});
 expect((await upload(token)).status).toBe(401);expect((await upload("synthetic-admin-test-password")).status).not.toBe(401);
});

test("regenerating the token invalidates the old token and every admin session; --revoke disables administration",async()=>{
 const {origin,db,token:first}=setup();const admin=await login(origin,first);
 const stored=db.db.query<{digest:string},[]>("SELECT digest FROM admin_access").get()!;
 expect(stored.digest).toMatch(/^[0-9a-f]{64}$/);expect(stored.digest).not.toContain(first.slice(10));
 const live=await adminSocket(origin,admin.cookie);const closed=new Promise<number>(resolve=>live.ws.once('close',code=>resolve(code)));
 const second=adminToken(db.path);expect(second).not.toBe(first);
 expect(await closed).toBe(4001);
 expect((await fetch(origin+"/api/admin/overview",{headers:{cookie:admin.cookie}})).status).toBe(401);
 expect((await login(origin,first)).response.status).toBe(401);
 const again=await login(origin,second);expect(again.response.status).toBe(200);
 await adminGet(origin,again.cookie,"/api/admin/overview");
 expect(adminToken(db.path,"--revoke")).toContain("disabled");
 expect((await fetch(origin+"/api/admin/overview",{headers:{cookie:again.cookie}})).status).toBe(503);
 expect((await login(origin,second)).response.status).toBe(503);
 expect(db.db.query("SELECT count(*) n FROM admin_tokens").get()).toEqual({n:0});
 expect(adminToken(db.path,"--revoke")).toContain("already disabled");
 // Neither token ever reaches a response or the log; failed attempts are important events.
 const third=adminToken(db.path);const admin3=await login(origin,third);
 const log=await adminGet(origin,admin3.cookie,"/api/admin/requests?path=/api/admin/login&limit=200");
 expect(log.rows.filter((r:any)=>r.status===401)).toHaveLength(1);expect(log.rows.find((r:any)=>r.status===401).important).toBe(true);
 const everything=JSON.stringify(log)+JSON.stringify(await adminGet(origin,admin3.cookie,"/api/admin/requests?limit=200"))+JSON.stringify(await adminGet(origin,admin3.cookie,"/api/admin/overview"))+JSON.stringify(db.db.query("SELECT * FROM request_log").all())+JSON.stringify(db.db.query("SELECT * FROM admin_access").all());
 for(const secret of [first,second,third,first.slice(10),third.slice(10)])expect(everything).not.toContain(secret);
});

async function adminSocket(origin:string,cookie:string,filters:Record<string,string>={}) {
 const {default:WebSocket}=await import("ws");
 const ws=new WebSocket(origin.replace('http:','ws:')+'/api/admin/live',{headers:{cookie,origin}});
 cleanup.unshift(()=>ws.terminate());
 const live={ws,changed:0,messages:[] as string[],important:[] as any[],
  /** Resolves on a `changed` notice beyond the first `count`. */
  async next(count:number){for(let i=0;i<300;i++){if(live.changed>count)return;await Bun.sleep(10)}throw Error('Missing admin change notice')},
  subscribe:(filters:Record<string,string>,on=true)=>ws.send(JSON.stringify({type:'subscribe',filters,live:on}))};
 ws.on('error',()=>{});
 ws.on('message',raw=>{const text=String(raw);live.messages.push(text);const message=JSON.parse(text);if(message.type==='changed')live.changed++;if(message.type==='important')live.important.push(message.data)});
 await new Promise<void>((resolve,reject)=>{ws.once('open',resolve);ws.once('error',reject)});
 // Subscribing asks for one refetch.
 live.subscribe(filters);
 await live.next(0);
 return live;
}

test('admin WebSocket says when data changed without sending it, ignores health probes and admin requests, throttles, pauses and resumes',async()=>{
 const {origin}=setup();const admin=await login(origin);const live=await adminSocket(origin,admin.cookie);
 await Bun.sleep(600);const before=live.changed;
 await fetch(origin+'/api/health');await fetch(origin+'/api/health?probe=1');
 // The administration's own reads would otherwise make it refetch itself.
 await adminGet(origin,admin.cookie,'/api/admin/overview');await adminGet(origin,admin.cookie,'/api/admin/requests');
 await Bun.sleep(700);expect(live.changed).toBe(before);
 await fetch(origin+'/websocket-proof');await live.next(before);
 const burst=live.changed;for(let i=0;i<20;i++)await fetch(origin+'/burst');
 await Bun.sleep(700);expect(live.changed-burst).toBeGreaterThanOrEqual(1);expect(live.changed-burst).toBeLessThanOrEqual(3);
 live.subscribe({},false);await Bun.sleep(600);const paused=live.changed;
 await fetch(origin+'/during-pause');await Bun.sleep(650);expect(live.changed).toBe(paused);
 live.subscribe({});await live.next(paused);
 // Notices carry no data; only important rows (here the admin login) do.
 expect(new Set(live.messages.filter(m=>JSON.parse(m).type!=="important"))).toEqual(new Set(['{"type":"changed"}']));
});

test('admin WebSocket rejects missing cookies and foreign origins; logout closes an open session',async()=>{
 const {origin}=setup();const admin=await login(origin);
 const {default:WebSocket}=await import('ws');
 async function rejected(headers:Record<string,string>){return new Promise<number>((resolve,reject)=>{
  const ws=new WebSocket(origin.replace('http:','ws:')+'/api/admin/live',{headers});cleanup.unshift(()=>ws.terminate());ws.on('error',()=>{});
  ws.on('unexpected-response',(_,response)=>{const status=response.statusCode!;response.destroy();ws.terminate();resolve(status)});ws.on('open',()=>reject(Error('Unexpected upgrade')));
 })}
 expect(await rejected({origin})).toBe(401);
 expect(await rejected({cookie:admin.cookie,origin:'https://foreign.example'})).toBe(403);
 const live=await adminSocket(origin,admin.cookie);
 live.subscribe({},false);
 const closed=new Promise<number>(resolve=>live.ws.once('close',code=>resolve(code)));
 await fetch(origin+'/api/admin/logout',{method:'POST',headers:{cookie:admin.cookie,origin}});
 expect(await closed).toBe(4001);
 expect(await rejected({cookie:admin.cookie,origin})).toBe(401);
});

test('admin WebSocket closes expired sessions and rejects invalid filter messages',async()=>{
 const {origin,db}=setup();const admin=await login(origin);const live=await adminSocket(origin,admin.cookie);
 const expired=new Promise<number>(resolve=>live.ws.once('close',code=>resolve(code)));
 db.db.exec('UPDATE admin_tokens SET expires_at=0');await fetch(origin+'/expiry-trigger');expect(await expired).toBe(4001);
 const second=await login(origin);const invalid=await adminSocket(origin,second.cookie);
 const rejected=new Promise<number>(resolve=>invalid.ws.once('close',code=>resolve(code)));
 invalid.subscribe({path:'x'.repeat(101)});expect(await rejected).toBe(1008);
});

// Administration data: overview, persistent request log, IPs, accounts and account actions.
const PASSWORD="a-long-test-password";
const dayAgo=(n:number)=>new Date(Date.now()-n*864e5).toISOString().slice(0,10);
const isoAgo=(n:number)=>new Date(Date.now()-n*864e5).toISOString();
async function adminGet(origin:string,cookie:string,path:string) {const response=await fetch(origin+path,{headers:{cookie}});expect(response.status).toBe(200);expect(response.headers.get("cache-control")).toBe("no-store");return response.json() as Promise<any>;}
async function call(origin:string,method:string,path:string,{token,body,headers={}}:{token?:string;body?:unknown;headers?:Record<string,string>}={}) {
 const response=await fetch(origin+path,{method,headers:{...(body===undefined?{}:{"content-type":"application/json"}),...(token?{authorization:"Bearer "+token}:{}),...headers},body:body===undefined?undefined:JSON.stringify(body)});
 const text=await response.text();return {status:response.status,body:text?JSON.parse(text):null};
}
const register=async(origin:string,username:string,headers:Record<string,string>={})=>(await call(origin,"POST","/api/auth/register",{body:{username,password:PASSWORD},headers})).body as {token:string;user:{id:string}};
async function eventually<T>(read:()=>Promise<T>,ok:(value:T)=>boolean) {let value=await read();for(let i=0;i<100&&!ok(value);i++){await Bun.sleep(30);value=await read();}return value;}

test("admin data endpoints require the admin session, never cache and validate their parameters",async()=>{
 const {origin}=setup();const user=await register(origin,"plain_user");
 const routes:[string,string][]=[["GET","/api/admin/overview"],["GET","/api/admin/requests"],["GET","/api/admin/ips"],["GET","/api/admin/users"],["GET",`/api/admin/users/${user.user.id}`],["POST",`/api/admin/users/${user.user.id}/revoke`],["DELETE",`/api/admin/users/${user.user.id}`]];
 for(const [method,path] of routes){
  expect((await fetch(origin+path,{method})).status).toBe(401);
  expect((await fetch(origin+path,{method,headers:{authorization:"Bearer "+user.token}})).status).toBe(401);
 }
 expect((await call(origin,"GET","/api/auth/me",{token:user.token})).status).toBe(200);
 const admin=await login(origin);
 for(const [method,path] of routes.filter(([m])=>m==="GET"))await adminGet(origin,admin.cookie,path);
 for(const path of ["/api/admin/requests?status=abc","/api/admin/requests?kind=bogus","/api/admin/requests?important=maybe","/api/admin/requests?from=-1","/api/admin/ips?days=0","/api/admin/ips?days=91","/api/admin/ips?sort=x","/api/admin/users?sort=x","/api/admin/users?filter=x","/api/admin/users?limit=500","/api/admin/users?page=-1","/api/admin/users?q="+"x".repeat(101)])
  expect((await fetch(origin+path,{headers:{cookie:admin.cookie}})).status).toBe(422);
 expect((await fetch(origin+"/api/admin/users/not-an-account",{headers:{cookie:admin.cookie}})).status).toBe(404);
 expect((await fetch(origin+"/api/admin/users/not-an-account/revoke",{method:"POST",headers:{cookie:admin.cookie}})).status).toBe(404);
 expect((await fetch(origin+"/api/admin/users/a%2Fb",{headers:{cookie:admin.cookie}})).status).toBe(404);
});

test("admin overview counts accounts, activity, solves, traffic, IPs and duels with 30-day series",async()=>{
 const {origin,db}=setup();
 const reg=await register(origin,"overview_user");await register(origin,"overview_two");
 for(const timeMs of [9000,10000])expect((await call(origin,"POST","/api/solves",{token:reg.token,body:{timeMs}})).status).toBe(200);
 expect((await fetch(origin+"/missing-page")).status).toBe(404);
 db.db.exec(`INSERT INTO users(id,username,password_hash,created_at) VALUES('old-reg','old_reg','x','${isoAgo(40)}'),('mid-guest','guest-mid',NULL,'${isoAgo(10)}');
  INSERT INTO solves(time_ms,user_id,created_at) VALUES(8000,'old-reg','${isoAgo(3)}'),(8500,'old-reg','${isoAgo(20)}');
  INSERT INTO user_activity(user_id,day,requests) VALUES('old-reg','${dayAgo(3)}',4),('mid-guest','${dayAgo(20)}',2);
  INSERT INTO traffic_daily(day,ip,requests,errors,server_errors,limited,first_at,last_at) VALUES('${dayAgo(3)}','198.51.100.1',10,2,1,1,0,0),('${dayAgo(20)}','198.51.100.2',5,0,0,0,0,0);
  INSERT INTO duel_games(race,game,event,ended_at,player1_name,player2_name,results) VALUES('r1',1,'333',${Date.now()},'a','b','[]'),('r2',1,'333',${Date.now()-10*864e5},'a','b','[]');`);
 const admin=await login(origin);
 const body=await adminGet(origin,admin.cookie,"/api/admin/overview");
 expect(body.users).toEqual({total:4,registered:3,guests:1,new:{today:2,d7:2,d30:3},active:{today:2,d7:3,d30:4}});
 expect(body.solves).toEqual({total:4,today:2,d7:3});
 // two registrations, two solves, the missing page and the admin login.
 expect(body.requests).toEqual({today:6,errorsToday:1,serverErrorsToday:0,rateLimitedToday:0});
 expect(body.ips).toEqual({today:1,d7:2,d30:3,live:1});
 expect(body.duels).toEqual({total:2,today:1,d7:1});
 expect(body.series).toHaveLength(30);expect(body.series.at(-1).day).toBe(dayAgo(0));expect(body.series[0].day).toBe(dayAgo(29));
 expect(body.series.at(-1)).toEqual({day:dayAgo(0),requests:6,ips:1,errors:1,serverErrors:0,limited:0,signups:2,registrations:2,active:2,solves:2,duels:1});
 expect(body.series.at(-4)).toEqual({day:dayAgo(3),requests:10,ips:1,errors:2,serverErrors:1,limited:1,signups:0,registrations:0,active:1,solves:1,duels:0});
 expect(body.series.at(-21)).toMatchObject({requests:5,active:1,solves:1});
 expect(body.series.at(-11)).toMatchObject({signups:1,registrations:0,duels:1});
 expect(body.server.version).toMatch(/^\d+\.\d+\.\d+$/);expect(body.server.uptimeMs).toBeGreaterThanOrEqual(0);
 expect(body.server.db.bytes).toBeGreaterThan(0);expect(body.server.db.logRows).toBe(6);
 expect(body.server.log).toMatchObject({retentionDays:30,maxRows:200000,maxImportantRows:50000,dropped:0});
});

test("persistent request log classifies, filters and paginates requests without secrets",async()=>{
 const {origin,db}=setup({CUBIX_TRUSTED_PROXIES:"127.0.0.1"});
 const user=await register(origin,"log_user",{"x-forwarded-for":"203.0.113.10","user-agent":"cubix-test-agent/1.0"});
 expect((await call(origin,"POST","/api/auth/login",{body:{username:"log_user",password:"wrong-secret-password"},headers:{"x-forwarded-for":"203.0.113.11"}})).status).toBe(401);
 expect((await call(origin,"GET","/api/auth/me",{token:user.token})).status).toBe(200);
 expect((await fetch(origin+"/missing.js?token=do-not-log-this")).status).toBe(404);
 expect((await call(origin,"GET","/api/nope?secret=do-not-log-this",{token:user.token})).status).toBe(404);
 const admin=await login(origin);const get=(query:string)=>adminGet(origin,admin.cookie,"/api/admin/requests"+query);
 const everything=await get("?limit=200");
 expect(everything.total).toBe(6);expect(everything.totalCapped).toBe(false);expect(everything.rows.map((r:any)=>r.id)).toEqual([...everything.rows.map((r:any)=>r.id)].sort((a:number,b:number)=>b-a));
 expect(everything.kinds).toContain("auth");
 const register_=everything.rows.find((r:any)=>r.path==="/api/auth/register");
 expect(register_).toMatchObject({method:"POST",status:200,ip:"203.0.113.10",kind:"auth",important:true,userId:user.user.id,username:"log_user",userAgent:"cubix-test-agent/1.0"});
 expect(typeof register_.at).toBe("number");expect(typeof register_.durationMs).toBe("number");
 expect(everything.rows.find((r:any)=>r.path==="/missing.js")).toMatchObject({status:404,kind:"not-found",important:false});
 expect(everything.rows.find((r:any)=>r.path==="/api/auth/me")).toMatchObject({kind:"api",important:false,userId:user.user.id});
 const important=await get("?important=1");
 expect(important.rows.map((r:any)=>r.path).sort()).toEqual(["/api/admin/login","/api/auth/login","/api/auth/register","/api/nope"]);
 expect(important.rows.find((r:any)=>r.path==="/api/nope")).toMatchObject({kind:"client-error",userId:user.user.id});
 const auth=await get("?kind=auth");expect(auth.total).toBe(2);expect(auth.rows.find((r:any)=>r.status===401)).toMatchObject({path:"/api/auth/login",ip:"203.0.113.11",userId:null});
 expect((await get("?status=4xx")).total).toBe(3);expect((await get("?status=404")).total).toBe(2);expect((await get("?status=5xx")).total).toBe(0);expect((await get("?status=error")).total).toBe(3);
 expect((await get("?ip=203.0.113.11")).rows.map((r:any)=>r.path)).toEqual(["/api/auth/login"]);
 expect((await get("?path=missing")).total).toBe(1);expect((await get("?method=post")).total).toBe(3);
 for(const who of ["log_user","LOG_USER",user.user.id])expect((await get("?user="+who)).rows.map((r:any)=>r.path)).toEqual(["/api/nope","/api/auth/me","/api/auth/register"]);
 // Admin reads are logged too: paginate a filter they do not change, or with the `before` cursor.
 const [first,second]=[await get("?important=1&limit=2&page=0"),await get("?important=1&limit=2&page=1")];
 expect(first.rows).toHaveLength(2);expect(second.rows).toHaveLength(2);expect(first.total).toBe(4);expect(second.total).toBe(4);expect(second.rows[0].id).toBeLessThan(first.rows[1].id);
 expect((await get("?important=1&page=2&limit=2")).rows).toEqual([]);
 expect((await get("?important=1&before="+first.rows[1].id+"&limit=2")).rows).toEqual(second.rows);
 expect((await get(`?from=${Date.now()+60000}`)).total).toBe(0);expect((await get(`?to=${Date.now()+60000}&from=0`)).total).toBeGreaterThanOrEqual(6);
 const stored=JSON.stringify(db.db.query("SELECT * FROM request_log").all());
 for(const text of [JSON.stringify(everything),stored])for(const secret of [user.token,"do-not-log-this","wrong-secret-password",PASSWORD,"token_hash","password_hash","?"])expect(text).not.toContain(secret);
});

test("persistent request log survives a restart",async()=>{
 const {origin,db,app}=setup();
 expect((await fetch(origin+"/persist-proof")).status).toBe(404);
 app.server.stop();
 const restarted=createRustApi(db.path);const again=`http://127.0.0.1:${restarted.server.port}`;
 const admin=await login(again);
 const body=await eventually(()=>adminGet(again,admin.cookie,"/api/admin/requests?path=persist-proof"),b=>b.total===1);
 expect(body.rows[0]).toMatchObject({path:"/persist-proof",status:404});
 expect((await adminGet(again,admin.cookie,"/api/admin/overview")).requests.today).toBeGreaterThanOrEqual(2);
});

test("admin IP listing aggregates requests, errors, rate limits and accounts per IP over a period",async()=>{
 const {origin,db}=setup({CUBIX_TRUSTED_PROXIES:"127.0.0.1"});
 const from=(ip:string)=>({"x-forwarded-for":ip});
 const user=await register(origin,"ip_user",from("203.0.113.20"));
 expect((await call(origin,"GET","/api/auth/me",{token:user.token,headers:from("203.0.113.20")})).status).toBe(200);
 await fetch(origin+"/nothing-here",{headers:from("203.0.113.20")});await fetch(origin+"/api/moves",{headers:from("203.0.113.21")});
 db.db.exec(`INSERT INTO traffic_daily(day,ip,requests,errors,server_errors,limited,first_at,last_at) VALUES('${dayAgo(10)}','198.51.100.9',7,1,0,3,1000,2000)`);
 const admin=await login(origin);const get=(query:string)=>adminGet(origin,admin.cookie,"/api/admin/ips"+query);
 const week=await get("");
 expect(week.days).toBe(7);expect(week.total).toBe(3);expect(week.rows.map((r:any)=>r.ip).sort()).toEqual(["127.0.0.1","203.0.113.20","203.0.113.21"]);
 const busy=week.rows.find((r:any)=>r.ip==="203.0.113.20");
 expect(busy).toMatchObject({requests:3,errors:1,serverErrors:0,limited:0,activeDays:1,userCount:1,users:[{id:user.user.id,username:"ip_user",isGuest:false}]});
 expect(busy.firstSeenAt).toBeLessThanOrEqual(busy.lastSeenAt);
 expect(week.rows.find((r:any)=>r.ip==="203.0.113.21").users).toEqual([]);
 const month=await get("?days=30");expect(month.total).toBe(4);expect(month.rows.find((r:any)=>r.ip==="198.51.100.9")).toMatchObject({requests:7,errors:1,limited:3});
 expect((await get("?days=30&sort=limited")).rows[0].ip).toBe("198.51.100.9");
 expect((await get("?sort=errors")).rows[0].ip).toBe("203.0.113.20");
 expect((await get("?sort=ip")).rows.map((r:any)=>r.ip)).toEqual(["127.0.0.1","203.0.113.20","203.0.113.21"]);
 expect((await get("?sort=ip&order=desc&limit=1&page=1")).rows.map((r:any)=>r.ip)).toEqual(["203.0.113.20"]);
 expect((await get("?q=203.0.113.2")).total).toBe(2);
 expect((await get("?user=ip_user")).rows.map((r:any)=>r.ip)).toEqual(["203.0.113.20"]);
});

test("admin account listing and detail report solves, activity, sessions, learned cases and duels",async()=>{
 const {origin,db}=setup();const {CASES}=await import("./backend");
 const alice=await register(origin,"alice");const bob=await register(origin,"bob");
 db.db.exec("INSERT INTO users(id,username) VALUES('old-guest','guest-old')");const guest={user:{id:"old-guest",username:"guest-old"}};
 // Registration and the direct INSERT can share a millisecond; give this ordering fixture distinct dates.
 const created=Date.now();
 for(const [i,id] of [alice.user.id,bob.user.id,guest.user.id].entries()) db.db.query("UPDATE users SET created_at=? WHERE id=?").run(new Date(created-2+i).toISOString(),id);
 for(const body of [{timeMs:10000},{timeMs:11000,penalty:"+2"},{timeMs:9000,penalty:"dnf"},{timeMs:3000,puzzle:"222"}])expect((await call(origin,"POST","/api/solves",{token:alice.token,body})).status).toBe(200);
 expect((await call(origin,"PUT","/api/learned",{token:alice.token,body:{caseId:CASES[0]!.id,learned:true}})).status).toBe(200);
 db.db.exec(`INSERT INTO duel_games(race,game,event,ended_at,player1_id,player1_name,player1_ao5,player2_id,player2_name,player2_ao5,winner,results) VALUES('race',1,'333',${Date.now()},'${bob.user.id}','bob',12000,'${alice.user.id}','alice',10000,1,'[]')`);
 const admin=await login(origin);const get=(query:string)=>adminGet(origin,admin.cookie,"/api/admin/users"+query);
 const list=await get("");
 expect(list.counts).toEqual({all:3,registered:2,guests:1});expect(list.total).toBe(3);
 expect(list.rows.map((r:any)=>r.username)).toEqual([guest.user.username,"bob","alice"]);
 const row=list.rows.find((r:any)=>r.username==="alice");
 expect(row).toMatchObject({id:alice.user.id,isGuest:false,solves:4,solves7d:4,learnedCases:1,duels:1,activeSessions:1});
 for(const key of ["createdAt","lastSeenAt","lastSolveAt"])expect(Math.abs(row[key]-Date.now())).toBeLessThan(60000);
 expect((await get("?filter=registered")).rows.map((r:any)=>r.username)).toEqual(["bob","alice"]);
 expect((await get("?filter=guests")).rows).toMatchObject([{id:guest.user.id,isGuest:true}]);
 expect((await get("?q=LIC")).rows.map((r:any)=>r.username)).toEqual(["alice"]);
 expect((await get("?q="+bob.user.id)).rows.map((r:any)=>r.username)).toEqual(["bob"]);
 expect((await get("?sort=solves")).rows[0].username).toBe("alice");
 // Most active this week: only accounts with solves in the last 7 days, the busiest first.
 const week=await get("?sort=solves7d&limit=8");expect(week.total).toBe(1);expect(week.rows).toMatchObject([{username:"alice",solves7d:4}]);
 expect((await get("?sort=username")).rows.map((r:any)=>r.username)).toEqual(["alice","bob",guest.user.username]);
 expect((await get("?sort=username&order=desc&limit=1&page=1")).rows.map((r:any)=>r.username)).toEqual(["bob"]);
 expect((await get("?sort=lastSeen")).rows).toHaveLength(3);
 const detail=await adminGet(origin,admin.cookie,"/api/admin/users/"+alice.user.id);
 expect(detail.user).toMatchObject({...row,lastSeenAt:detail.user.lastSeenAt,practiceSessions:0});
 expect(detail.puzzles).toMatchObject([{puzzleId:"333",solveMode:"standard",solves:3,dnf:1,trainingSolves:0,bestMs:10000,meanMs:11500},{puzzleId:"222",solves:1,bestMs:3000}]);
 expect(detail.activity).toHaveLength(90);expect(detail.activity.at(-1)).toMatchObject({day:dayAgo(0),active:true,solves:4});expect(detail.activity.at(-1).requests).toBeGreaterThanOrEqual(6);
 expect(detail.recentSolves.map((s:any)=>s.timeMs)).toEqual([3000,9000,11000,10000]);expect(detail.recentSolves[2]).toMatchObject({penalty:"+2",effectiveMs:13000});
 expect(detail.recentRequests.filter((r:any)=>r.path==="/api/solves")).toHaveLength(4);
 expect(detail.sessions).toHaveLength(1);expect(detail.sessions[0].id).toMatch(/^[0-9a-f]{12}$/);
 expect(detail.sessions[0].expiresAt-detail.sessions[0].createdAt).toBe(30*864e5);expect(typeof detail.sessions[0].lastUsedAt).toBe("number");
 expect(detail.duels).toMatchObject({played:1,won:1,lost:0,drawn:0,recent:[{event:"333",opponent:"bob",opponentId:bob.user.id,ao5:10000,opponentAo5:12000,result:"win"}]});
 expect(detail.ips).toMatchObject([{ip:"127.0.0.1",days:1}]);
 expect((await adminGet(origin,admin.cookie,"/api/admin/users/"+bob.user.id)).duels.recent[0].result).toBe("loss");
 const text=JSON.stringify(detail)+JSON.stringify(list);for(const secret of [alice.token,"token_hash","password_hash"])expect(text).not.toContain(secret);
});

test("admin can sign an account out everywhere and delete it with all its data; both are logged",async()=>{
 const {origin,db}=setup();const victim=await register(origin,"victim");const other=await register(origin,"bystander");
 expect((await call(origin,"POST","/api/solves",{token:victim.token,body:{timeMs:9000}})).status).toBe(200);
 expect((await call(origin,"POST","/api/solves",{token:other.token,body:{timeMs:9000}})).status).toBe(200);
 const admin=await login(origin);const headers={cookie:admin.cookie,origin};
 expect((await fetch(origin+`/api/admin/users/${victim.user.id}/revoke`,{method:"POST",headers:{cookie:admin.cookie,origin:"https://foreign.example"}})).status).toBe(403);
 const revoked=await fetch(origin+`/api/admin/users/${victim.user.id}/revoke`,{method:"POST",headers});
 expect(revoked.status).toBe(200);expect(await revoked.json()).toEqual({ok:true,revoked:1});
 expect((await call(origin,"GET","/api/auth/me",{token:victim.token})).status).toBe(401);
 expect((await call(origin,"GET","/api/auth/me",{token:other.token})).status).toBe(200);
 const again=(await call(origin,"POST","/api/auth/login",{body:{username:"victim",password:PASSWORD}})).body;
 expect((await fetch(origin+`/api/admin/users/${victim.user.id}`,{method:"DELETE",headers:{cookie:admin.cookie,origin:"https://foreign.example"}})).status).toBe(403);
 const deleted=await fetch(origin+`/api/admin/users/${victim.user.id}`,{method:"DELETE",headers});
 expect(deleted.status).toBe(200);expect(await deleted.json()).toEqual({ok:true,username:"victim",solves:1,sessions:0});
 expect((await call(origin,"GET","/api/auth/me",{token:again.token})).status).toBe(401);
 expect((await fetch(origin+`/api/admin/users/${victim.user.id}`,{headers:{cookie:admin.cookie}})).status).toBe(404);
 expect((await fetch(origin+`/api/admin/users/${victim.user.id}`,{method:"DELETE",headers})).status).toBe(404);
 for(const table of ["users WHERE id=?","solves WHERE user_id=?","auth_tokens WHERE user_id=?","sync_changes WHERE user_id=?","user_activity WHERE user_id=?","traffic_daily_users WHERE user_id=?"])
  expect(db.db.query(`SELECT count(*) n FROM ${table}`).get(victim.user.id)).toEqual({n:0});
 expect(db.db.query("SELECT count(*) n FROM solves").get()).toEqual({n:1});
 const log=await adminGet(origin,admin.cookie,"/api/admin/requests?important=1");
 expect(log.rows.find((r:any)=>r.path.endsWith("/revoke"))).toMatchObject({method:"POST",status:200,kind:"admin",userId:victim.user.id});
 expect(log.rows.find((r:any)=>r.method==="DELETE"&&r.status===200)).toMatchObject({path:`/api/admin/users/${victim.user.id}`,kind:"account",userId:victim.user.id});
 // The refused (403) and repeated (404) deletions are account events too.
 expect((await adminGet(origin,admin.cookie,"/api/admin/requests?kind=account")).rows.map((r:any)=>r.status)).toEqual([404,200,403]);
 // Only the audit rows of the actions keep the deleted account's id.
 expect((await adminGet(origin,admin.cookie,"/api/admin/requests?user="+victim.user.id)).rows.map((r:any)=>r.method+" "+r.status)).toEqual(["DELETE 200","POST 200"]);
 const users=await adminGet(origin,admin.cookie,"/api/admin/users");expect(users.counts).toEqual({all:1,registered:1,guests:0});
});

test("admin WebSocket pushes newly logged important requests while live",async()=>{
 const {origin}=setup();const admin=await login(origin);const live=await adminSocket(origin,admin.cookie);
 await fetch(origin+"/quiet-page");
 expect((await call(origin,"POST","/api/auth/login",{body:{username:"nobody",password:"wrong-secret-password"}})).status).toBe(401);
 const event:any=await eventually(async()=>live.important.find((r:any)=>r.path==="/api/auth/login"),Boolean);
 expect(event).toMatchObject({status:401,kind:"auth",important:true,method:"POST"});expect(typeof event.id).toBe("number");
 expect(live.important.some((r:any)=>r.path==="/quiet-page")).toBe(false);
 expect(JSON.stringify(live.important)).not.toContain("wrong-secret-password");
});

test("finished duels are recorded for the overview and both accounts",async()=>{
 const {origin}=setup();const alice=await register(origin,"duel_alice");const bob=await register(origin,"duel_bob");
 async function player(token:string) {
  const ws=new WebSocket(origin.replace("http:","ws:")+"/api/duel");const inbox:any[]=[];ws.onmessage=({data})=>inbox.push(JSON.parse(String(data)));
  await new Promise(resolve=>(ws.onopen=resolve));cleanup.unshift(()=>ws.close());
  const next=async(test:(m:any)=>boolean)=>{for(let i=0;i<300;i++){const found=inbox.find(test);if(found)return found;await Bun.sleep(10);}throw Error("Missing duel message");};
  return {ws,next,send:(m:object)=>ws.send(JSON.stringify(m))};
 }
 const a=await player(alice.token),b=await player(bob.token);
 a.send({type:"queue",event:"333",level:10000,token:alice.token});b.send({type:"queue",event:"333",level:10500,token:bob.token});
 const [ma]=await Promise.all([a.next(m=>m.type==="match"),b.next(m=>m.type==="match")]);
 const [host,guest]=ma.host?[a,b]:[b,a];const aliceSeat=ma.seat;
 host.send({type:"scrambles",list:["R","U","F","L","D"]});await guest.next(m=>m.type==="state"&&m.scrambles.length===5);
 for(let round=0;round<5;round++){
  a.send({type:"solve",round,ms:10000+round,penalty:"none"});b.send({type:"solve",round,ms:12000+round,penalty:round===4?"dnf":"none"});
  await a.next(m=>m.type==="state"&&m.results.every((r:any[])=>r[round]));
 }
 a.ws.close();b.ws.close();
 const admin=await login(origin);
 const overview=await eventually(()=>adminGet(origin,admin.cookie,"/api/admin/overview"),o=>o.duels.total===1);
 expect(overview.duels).toEqual({total:1,today:1,d7:1});expect(overview.series.at(-1).duels).toBe(1);
 const detail=await adminGet(origin,admin.cookie,"/api/admin/users/"+alice.user.id);
 expect(detail.duels).toMatchObject({played:1,won:1,lost:0,recent:[{opponent:"duel_bob",opponentId:bob.user.id,ao5:10002,opponentAo5:12002,result:"win"}]});
 expect(detail.user.duels).toBe(1);expect(aliceSeat===0||aliceSeat===1).toBe(true);
 const log=await adminGet(origin,admin.cookie,"/api/admin/requests?kind=duel");expect(log.total).toBe(2);expect(log.rows[0]).toMatchObject({status:101,important:true});
});

test("rate-limited requests are logged as important and counted per day and per IP",async()=>{
 // The admin's own IP shares the limit: the start-up health probe, the login and four reads fit.
 const {origin}=setup({CUBIX_TRUSTED_PROXIES:"127.0.0.1",CUBIX_RATE_LIMIT:"8"});
 const statuses=[];for(let i=0;i<10;i++)statuses.push((await fetch(origin+"/api/moves",{headers:{"x-forwarded-for":"203.0.113.30"}})).status);
 expect(statuses.filter(s=>s===429).length).toBeGreaterThanOrEqual(2);const limited=statuses.filter(s=>s===429).length;
 const admin=await login(origin);
 const log=await adminGet(origin,admin.cookie,"/api/admin/requests?kind=rate-limit");
 expect(log.total).toBe(limited);expect(log.rows[0]).toMatchObject({ip:"203.0.113.30",status:429,important:true,path:"/api/moves"});
 expect((await adminGet(origin,admin.cookie,"/api/admin/requests?important=0&ip=203.0.113.30")).total).toBe(10-limited);
 expect((await adminGet(origin,admin.cookie,"/api/admin/overview")).requests).toMatchObject({rateLimitedToday:limited,errorsToday:limited});
 expect((await adminGet(origin,admin.cookie,"/api/admin/ips?sort=limited")).rows[0]).toMatchObject({ip:"203.0.113.30",requests:10,limited,errors:limited});
});
