package main

import _ "embed"

//go:embed embed/catalog.json
var catalogJSON []byte

type Catalog struct {
	cases []any
	sets  any
	moves any
	byID  map[string]M
}

// catalogLoad: the whole catalogue comes from `data/catalog.json`, generated by `bun run build:catalog`.
func catalogLoad() *Catalog {
	doc, err := decodeJSON(catalogJSON)
	if err != nil {
		panic("catalog.json: " + err.Error())
	}
	cases, ok := asArray(idx(doc, "cases"))
	if !ok {
		panic("cases")
	}
	byID := make(map[string]M, len(cases))
	for _, c := range cases {
		id, ok := asStr(idx(c, "id"))
		if !ok {
			panic("case id")
		}
		byID[id] = c.(M)
	}
	return &Catalog{cases: cases, sets: idx(doc, "sets"), moves: idx(doc, "moves"), byID: byID}
}
