/**
 * Bundle cubing.js's search engine ("inside" API) into one self-contained HTML page.
 * The app loads it in a hidden WebView: Hermes has no WebAssembly or module workers,
 * and cubing.js's random-state scramblers need a browser engine.
 */
import { resolve } from "node:path";
import { mkdir, writeFile } from "node:fs/promises";

const repo = resolve(import.meta.dir, "../..");
const chunks = resolve(repo, "node_modules/cubing/dist/lib/cubing/chunks");
const entry = resolve(import.meta.dir, "scrambler-entry.ts");
const result = await Bun.build({
  entrypoints: [entry], target: "browser", format: "iife", minify: true, splitting: false,
  define: { "import.meta.url": '"file:///scrambler.js"' },
  plugins: [{
    name: "expose-inside-api",
    setup(build) {
      // The inside module only exposes its API over comlink; publish it on the page instead.
      build.onLoad({ filter: /\/chunks\/inside-[^/]+\.js$/ }, async args => {
        const text = await Bun.file(args.path).text();
        return { contents: text.replace(/\nexpose\(insideAPI\);/, "\nglobalThis.__cubixInside = insideAPI;"), loader: "js" };
      });
    },
  }],
});
if (!result.success) { console.error(result.logs.join("\n")); process.exit(1); }
const js = await result.outputs[0].text();
const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"></head><body><script>${js.replace(/<\/script>/g, "<\\/script>")}</script></body></html>`;
const out = resolve(import.meta.dir, "../src/scrambler/scrambler-html.ts");
await mkdir(resolve(import.meta.dir, "../src/scrambler"), { recursive: true });
await writeFile(out, `// Generated by scripts/build-scrambler.ts from cubing ${JSON.parse(await Bun.file(resolve(repo, "node_modules/cubing/package.json")).text()).version}. Do not edit.\nexport const SCRAMBLER_HTML = ${JSON.stringify(html)};\n`);
console.log(`Wrote ${out} (${(html.length / 1024).toFixed(0)} KB) from ${chunks}`);
