/**
 * Copy the pre-rendered case diagrams of the non-cube puzzles and generate a static
 * `require` map, so `CaseDiagram` can resolve `c.diagram` ("/cases/x.svg") at runtime.
 * Styles are inlined with svgo because react-native-svg has no CSS support.
 */
import { readdir, mkdir, writeFile, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { optimize } from "svgo";

const source = resolve(import.meta.dir, "../../assets/cases");
const target = resolve(import.meta.dir, "../assets/cases");
await mkdir(target, { recursive: true });
const files = (await readdir(source)).filter(name => name.endsWith(".svg")).sort();
for (const name of files) {
  const svg = await readFile(resolve(source, name), "utf8");
  const { data } = optimize(svg, { multipass: true, plugins: [
    { name: "preset-default", params: { overrides: { inlineStyles: { onlyMatchedOnce: false }, cleanupIds: false } } },
    "convertStyleToAttrs", "removeStyleElement", "removeXMLNS",
  ] });
  await writeFile(resolve(target, name), data);
}
const lines = files.map(name => `  ${JSON.stringify("/cases/" + name)}: require("../../assets/cases/${name}").default,`);
const out = resolve(import.meta.dir, "../src/components/caseDiagrams.ts");
await writeFile(out, `// Generated by scripts/build-cases.ts. Do not edit.\nimport type { ComponentType } from "react";\nimport type { SvgProps } from "react-native-svg";\nexport const CASE_DIAGRAMS: Record<string, ComponentType<SvgProps>> = {\n${lines.join("\n")}\n};\n`);
console.log(`Wrote ${files.length} diagrams to ${target} and ${out}`);
