/**
 * Bundle the camera page of the assisted solve (scripts/scan-entry.ts, with the web's face reader) into one
 * self-contained HTML page: the app shows it in a WebView, the only place a phone's camera stream can be read
 * without a native camera module.
 */
import { resolve } from "node:path";
import { mkdir, writeFile } from "node:fs/promises";

const result = await Bun.build({ entrypoints: [resolve(import.meta.dir, "scan-entry.ts")], target: "browser", format: "iife", minify: true });
if (!result.success) { console.error(result.logs.join("\n")); process.exit(1); }
const js = await result.outputs[0]!.text();
const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no">
<style>html,body{margin:0;height:100%;overflow:hidden;background:transparent}#view{position:fixed;inset:0}video,svg{position:absolute;inset:0;width:100%;height:100%}video{object-fit:cover}</style>
</head><body><div id="view"><video autoplay playsinline muted></video><svg id="overlay" viewBox="0 0 480 480" preserveAspectRatio="xMidYMid slice"></svg></div><script>${js.replace(/<\/script>/g, "<\\/script>")}</script></body></html>`;
const out = resolve(import.meta.dir, "../src/scan/scan-html.ts");
await mkdir(resolve(import.meta.dir, "../src/scan"), { recursive: true });
await writeFile(out, `// Generated by scripts/build-scan.ts. Do not edit.\nexport const SCAN_HTML = ${JSON.stringify(html)};\n`);
console.log(`Wrote ${out} (${(html.length / 1024).toFixed(0)} KB)`);
