/**
 * Copy the rasterised case diagrams of the non-cube puzzles (`assets/cases/*.png`, from the
 * repository's build-case-images.ts) and generate a static `require` map, so `CaseDiagram` can
 * resolve `c.diagram` ("/cases/x.svg") to a bundled image at runtime. Bitmaps rather than the SVGs:
 * react-native-svg mounts one native view per element and these diagrams hold hundreds.
 */
import { copyFile, mkdir, readdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const source = resolve(import.meta.dir, "../../assets/cases");
const target = resolve(import.meta.dir, "../assets/cases");
await mkdir(target, { recursive: true });
const files = (await readdir(source)).filter(name => name.endsWith(".png")).sort();
if (!files.length) throw new Error(`No case images in ${source}: run \`bun scripts/build-case-images.ts\` at the repository root.`);
for (const name of files) await copyFile(resolve(source, name), resolve(target, name));
const lines = files.map(name => `  ${JSON.stringify("/cases/" + name.replace(/\.png$/, ".svg"))}: require("../../assets/cases/${name}"),`);
const out = resolve(import.meta.dir, "../src/components/caseDiagrams.ts");
await writeFile(out, `// Generated by scripts/build-cases.ts. Do not edit.\nimport type { ImageSourcePropType } from "react-native";\nexport const CASE_DIAGRAMS: Record<string, ImageSourcePropType> = {\n${lines.join("\n")}\n};\n`);
console.log(`Wrote ${files.length} diagrams to ${target} and ${out}`);
