use serde_json::Value;
use std::collections::HashMap;
pub struct Catalog {
    pub cases: Value,
    pub sets: Value,
    pub moves: Value,
    pub by_id: HashMap<String, Value>,
}
impl Catalog {
    /// The whole catalogue comes from `data/catalog.json`, generated by `bun run build:catalog`.
    pub fn load() -> Self {
        let mut doc: Value =
            serde_json::from_str(include_str!("../../data/catalog.json")).expect("catalog.json");
        let cases = doc["cases"].take();
        Self {
            by_id: cases
                .as_array()
                .expect("cases")
                .iter()
                .map(|c| (c["id"].as_str().expect("case id").to_owned(), c.clone()))
                .collect(),
            cases,
            sets: doc["sets"].take(),
            moves: doc["moves"].take(),
        }
    }
}
