import type { PuzzleId } from '../../src/shared/puzzles';
import { MethodsGuide } from './Methods';
import { NotationContent } from '../renderer/notation';
import { GUIDES, type Guide } from './pages';

export function GuideContent({ page, puzzle = '333', method = '' }: { page: Guide; puzzle?: PuzzleId; method?: string }) {
  return <section className="flex max-w-2xl flex-col text-sm leading-relaxed [&_h2]:mt-8 [&_h2]:mb-2 [&_h2]:text-base [&_h2]:font-semibold [&_h2]:tracking-tight [&_h2]:text-foreground [&_p]:mb-3 [&_p]:text-muted-foreground [&_li]:text-muted-foreground [&_strong]:font-medium [&_strong]:text-foreground [&_a]:font-medium [&_a]:text-primary [&_a]:underline-offset-4 [&_a:hover]:underline [&_ol]:mb-3 [&_ol]:flex [&_ol]:list-decimal [&_ol]:flex-col [&_ol]:gap-2 [&_ol]:pl-5 [&_details]:border-b [&_details]:py-3 [&_summary]:cursor-pointer [&_summary]:font-medium [&_summary]:text-foreground [&_details_p]:mt-2 [&_details_p]:mb-0" aria-label="About Cubix">
    <header className="mb-4"><h1 className="text-2xl font-semibold tracking-tight text-balance">{GUIDES[page].heading}</h1></header>
    {page === 'overviewGuide' && <>
      <p className="text-base text-foreground/80!">Cubix is a free cube timer and algorithm trainer for desktop and mobile. Sign in and tell Cubix the puzzles you can solve to start.</p>
      <div className="mt-4 grid gap-x-8 gap-y-2 sm:grid-cols-2 [&_h2]:mt-2 [&_p_a]:mr-3">
        <section><h2>Timer</h2><p>Apply the scramble, hold Space (or touch the screen), release to start, press any key to stop. Times, Ao5 and Ao12 are kept per puzzle.</p><p><a href="/guides/how-to-use-a-cube-timer/">Timer guide</a><a href="/guides/cube-duel/">Duel guide</a><a href="/guides/cubing-coaching/">Coaching guide</a></p></section>
        <section><h2>Algorithms</h2><p>F2L, OLL and PLL cases with diagrams, setups and algorithms from trusted sources. 2×2 to 7×7, Square-1, Pyraminx, Skewb, Megaminx and Clock are included.</p><p><a href="/guides/cube-algorithms/">Algorithm guide</a></p></section>
        <section><h2>Training</h2><p>Pick the cases you want to drill. Cubix shows a setup, times your execution and tracks your progress per case.</p><p><a href="/guides/algorithm-training/">Training guide</a></p></section>
        <section><h2>Averages</h2><p>Best, mean, Ao5 and Ao12 with +2 and DNF handled the WCA way.</p><p><a href="/guides/ao5-ao12/">Ao5 and Ao12 explained</a></p></section>
      </div>
      <h2>Learning a new puzzle</h2>
      <p>Picking a puzzle opens its timer. A puzzle you cannot solve yet opens on its course in Learn instead, and asks whether you want to learn it: Start learning opens the recommended method, Unlock everything opens the puzzle everywhere, and Not now goes back to the previous puzzle. Until its course is finished, Timer, Algorithms, Training and Duel are greyed for that puzzle; clicking one offers to skip the tutorial, which opens them at once. Finishing a course with Finish does the same.</p>
      <h2>Your account page</h2>
      <p>Change the puzzles you can solve, and the methods you use on each, with Redo the introduction in the guides; Replay tour replays the guided visit.</p>
      <p>The Account tab is your dashboard. Overview shows four cards for the selected puzzle and solve mode: your best time with Ao5 and Ao12, the cases you have trained and learned, your unlocked achievements with the next goal, and your active days. Click a card to open its section.</p>
      <p>Timer lists best, mean, Ao5 and Ao12 for one puzzle, scramble type and solve mode, with a chart of every solve and the rolling Ao5; hover the chart to read a solve, click a row to edit it. Training shows each case with its best attempt; open one for its own chart. Achievements groups goals per puzzle. Settings holds the theme, the accent colour and sign-out.</p>
      <h2>Questions</h2>
      <details><summary>Is Cubix free? Do I need an account?</summary><p>Yes, it is free, with a free account: your practice is saved on your device first, then synchronised between your devices with achievements that follow you everywhere.</p></details>
      <details><summary>Does it work offline?</summary><p>Once installed, the app works without a connection. Sync needs a connection.</p></details>
      <details><summary>Does it work on a phone?</summary><p>Yes. Hold a free area of the screen to arm the timer, release to start, tap to stop.</p></details>
      <details><summary>Is this an official competition timer?</summary><p>No. Cubix is a practice tool and is not affiliated with Rubik’s or the World Cube Association.</p></details>
    </>}
    {page === 'algorithmsGuide' && <>
      <p className="text-base text-foreground/80!">The library lists every case with its diagram, setup and algorithms. Open a case to compare its algorithms and see your statistics.</p>
      <h2>3D case player</h2><p>The cube of a case shows the case, then plays its algorithm move by move: play or pause, step one move back or forward, restart, change the speed, or drag the bar under it to any point. The move being played is lit in the algorithm; click a move to turn it, click another algorithm to play that one, and press Replay to watch again from the case. Space plays or pauses and the arrow keys step while the player has the focus. Drag the cube to see it from another angle and double-click it to come back. Blue is the front reference and red is the right reference. OLL highlights orientation, PLL highlights the last layer, and F2L hides last-layer pieces. Notation, in the toolbar, explains every move letter on the cube.</p>
      <h2>Browse by stage</h2><p>F2L pairs a corner and an edge to finish the first two layers. OLL orients the last layer. PLL permutes it. ZBLL finishes the last layer in one algorithm when its edges are already oriented, sorted by corner pattern (T, U, L, Pi, H, S, AS). Use the stage tabs to jump between them and the set switches to choose 2-look or full variants.</p>
      <h2>Solving methods</h2><p>Methods in the toolbar opens a short explanation of each way to solve the selected puzzle, such as CFOP, Roux or ZZ on the 3×3. See <a href="/guides/solving-methods/">Solving methods</a><a href="/guides/cube-notation/">Notation</a>.</p>
      <h2>From reference to practice</h2><p>Press Train on a case or Train all on a group to open the <a href="/training/">trainer</a> with that selection. Trained cases show their best and mean time on their card.</p>
      <p>Sources are shown next to each algorithm. The <a href="https://github.com/Vitrixxl/cubix">Cubix source repository</a> documents the catalogue.</p>
    </>}
    {page === 'trainingGuide' && <>
      <p className="text-base text-foreground/80!">The trainer repeats the cases you choose so you can work on recognition and execution separately from full solves.</p>
      <h2>Choose what to train</h2><p>Training opens on its setup screen: the modes are listed on the left and the chosen one is described on the right with its Start button. The back arrow in the header of a running training returns to this screen; your selection and settings are kept.</p>
      <h2>Cross + 1 (3×3)</h2><p>Cross + 1 trains the first block. After scrambling, turn the cube over with z2 so white is on the bottom and green stays in front. The block is a back F2L pair (BR or BL) with its two cross edges, a 2×2×2. Choose 3, 4 or 5 moves; every scramble is a random cube whose shortest back block takes exactly that number of face turns, the other cross edges being anywhere. Build the block, finish the cross and the pair if you like, then stop the timer. Show solution lists optimal ways to build the block in that orientation and which block each one builds. The number of moves can be changed in the header; times are kept per move count and appear in Account → Timer under their own scramble type.</p>
      <h2>Review everything learned</h2><p>Choose Review learned on the setup screen to mix every case marked learned for the selected puzzle, across all stages and sets. Each timed attempt or Next picks another case. New learned cases join automatically; removing a learned mark removes the case from review after the current attempt. Daily assignments and your free-practice selection are preserved.</p>
      <h2>Daily learning (3×3)</h2><p>Choose Learn F2L, Learn OLL or Learn PLL on the 3×3 setup screen. Repeat the algorithm of the day as often as you like, then mark it learned. It stays assigned across restarts and missed days until learned; the next case arrives on the following local calendar day. You can keep practising today’s case after learning it, or undo Learned. Open Groups and use the up and down arrows to choose the order of case families. The order is saved per track on this device. Reordering keeps today’s case and affects future assignments; already learned cases are skipped. Each track remembers its own case. Press Train learned to repeat every case of the track you have already marked learned, one random case per attempt; press it again to return to today’s case. Free practice restores your manual selection. Daily assignments stay on this device for each account; learned marks synchronise with your account.</p>
      <h2>Set up a session</h2><ol><li>Choose Free practice, select the cases to practise (a whole set, a group or single cases) and press Start.</li><li>Apply the setup shown on your cube.</li><li>Hold Space (or a free area of the screen), release to start, press any key to stop.</li><li>Review the session in Times. Undo removes the last time.</li></ol>
      <h2>Tips</h2><p>Start with a few cases you confuse. Keep the solution hidden to train recognition, reveal it when needed. Random U turns before the setup make recognition harder, as in a real solve.</p>
      <p>For full solves, open the <a href="/">timer</a>. The <a href="/guides/ao5-ao12/">averages guide</a> explains the statistics.</p>
    </>}
    {page === 'timerGuide' && <>
      <p className="text-base text-foreground/80!">Cubix times physical solves with your keyboard or touchscreen. <a href="/">Open the timer</a> and follow these steps.</p>
      <h2>1. Choose a puzzle and scramble</h2><p>The puzzle selector at the top of the sidebar changes the puzzle everywhere. The scramble type, solve mode and entry are chosen in the page header, next to Replay and New scramble. Normal generates a scramble for the selected WCA event. The session figures run along the bottom: best in green, worst in red, the current Ao5 and Ao12 in the accent colour, with their best values beside them.</p>
      <p>The 3D cube plays the complete scramble in three seconds for 2×2 and 3×3 cubes. Each larger size adds one second, from four seconds for 4×4 to seven seconds for 7×7. Drag it to change the viewing angle or use Replay to watch the scramble again. Long scrambles scroll inside their text area while the cube and timer remain visible.</p>
      <h2>2. Start</h2><p>Hold Space for 0.3 seconds until the time turns green, then release. Releasing early cancels. On a phone, hold a free area of the screen and release when ready.</p>
      <h2>3. Stop and review</h2><p>Press any key or tap the screen to stop. The time is saved and the next scramble appears. Buttons under the time let you add a +2, mark it DNF, write a comment or delete it. Each time in the Times list has the same +2, DNF and delete buttons, and its i button opens the solve with its scramble and comment.</p>
      <h2>Typing and casual entry</h2><p>The entry menu next to the scramble type chooses how times come in. Timer is the built-in timer. Typing replaces it with a field for a time measured on an external timer such as a speed-stacking mat: type it and press Enter. Bare digits are read from the right, so 1234 is 12.34 and 12345 is 1:23.45; 12.34 and 1:23.45 work too. Casual runs the timer without recording anything: the time is shown, then forgotten, and the session, statistics and profile stay untouched.</p>
      <h2>Explore your progress</h2><p>In Account → Timer, the chart sits above your times. Scroll over the chart to zoom around the pointer, or drag across it to select a period. Hold Shift while dragging to move through the history; horizontal trackpad scrolling also moves the visible period. Dates along the bottom show the visible period and the list below follows it. Hover to read a single time and its rolling Ao5. Double-click the chart or use Reset zoom inside it to return to the full history. With the chart focused, use + and − to zoom, the arrow keys to move, Home to reset, and Escape to cancel a selection. The summary cards always describe the full history for the selected puzzle and mode.</p>
      <h2>Modes</h2><p>Standard, one-handed and blindfolded keep separate histories. Blindfolded time includes memorisation. Times are saved on your device first, then synchronised with your account.</p>
      <p>For official competitions, follow the <a href="https://www.worldcubeassociation.org/regulations/">WCA Regulations</a>.</p>
    </>}
    {page === 'duelGuide' && <>
      <p className="text-base text-foreground/80!">Duel races you against another cuber, live, on the same scrambles. Open it from the crossed swords in the sidebar (Alt+5).</p>
      <h2>1. Find an opponent</h2><p>Choose the puzzle in the sidebar, then Find an opponent. There is no rating: your level is the mean of your last twelve timer solves on that puzzle, without the best and the worst, once five of them count. You meet the player searching the same puzzle whose level is closest to yours. The range accepted widens the longer you wait, from 15% at once to anyone after 30 seconds, so a quiet moment still gives you a race. Without a level you first meet other new players, then anyone after 10 seconds. Players race under their username.</p>
      <h2>2. Race five rounds</h2><p>Both of you get the same five scrambles, one round at a time. Your timer is on the left, your opponent's on the right, with the scrambled cube between them: drag it to turn it, or hide it with its × or the Cube cell of the header. Start and stop like on the timer page. You see your opponent hold, start and stop as it happens, and the next round opens once you have both finished.</p>
      <h2>3. +2, DNF and Cancel</h2><p>The cells at the end of your row put a +2 or a DNF on your latest solve, or take it off again. Cancel takes your solve back so you can redo it on the same scramble, as long as your opponent has not finished that round.</p>
      <h2>4. The result</h2><p>After five rounds the best Ao5 wins: best and worst dropped, one DNF counts as the worst, two make the average DNF. The result dialog offers a rematch, which starts once you both accept it on five new scrambles, or a new opponent. Your recent battles appear in Account.</p>
      <h2>Chat</h2><p>The chat runs beside the race on wide screens and behind the Chat cell otherwise. Messages last as long as the race.</p>
    </>}
    {page === 'coachingGuide' && <>
      <p className="text-base text-foreground/80!">Coaching puts you in a video call with a cuber who teaches. Open it from the headset in the sidebar (Alt+6).</p>
      <h2>1. Find a coach</h2><p>Find a coach lists every coach with their rating, the events they teach, their best times, their price per session and their next free slot. Search by name, language or method, or keep one event. A coach's page shows who they are, what their students wrote about them and the share of each rating.</p>
      <h2>2. Book a session</h2><p>A coach's page opens on booking, in three numbered steps. The calendar shows the coach's free slots over the next four weeks, month by month and in your own time zone: click a time in a day to pick it, or the day to see all its times. Pick a day, then a time, say what you want to work on and Book: the session is confirmed at once. Payment is not asked for yet. Slots start an hour from now at the earliest.</p>
      <h2>3. Talk with your coach</h2><p>Booking opens a conversation with the coach, and Message on a coach's page opens one before booking. Messages arrive live; the sidebar counts the unread ones and a notice offers to open them from any page. To show your solves, send pictures (up to 10 MB) or videos (up to 64 MB): pick them with the clip beside the message box, paste them, or drop them on the conversation. Only you and the other party can open them.</p>
      <h2>4. The call</h2><p>Sessions lists what is coming. Join call opens a quarter of an hour before the session and stays open half an hour after it; when the other party is already in, you are told on any page. The browser asks once for the camera and the microphone. In the call you can mute, turn the camera off, share your screen to show an algorithm sheet, and keep the chat beside the video. Cancel a session from its row: the other party is told and the slot opens again.</p>
      <h2>5. Review</h2><p>Once a session is over, Review gives the coach one to five stars and a few words. You can change your review later; it appears on the coach's page under your username.</p>
      <h2>Becoming a coach</h2><p>Become a coach sends the team your e-mail address, the events you would teach, your level and how you would coach. The team answers by e-mail. Once you are accepted, the Coaching section gains your Dashboard, Students, Schedule and Coach profile.</p>
      <h2>For coaches</h2><p>Schedule shows your month as a calendar, on your own clock, with the sessions booked in it: click one to see who booked, their practice and your notes, and open their whole profile. Edit availability asks what you want to change. Add a date opens hours on days you are usually closed, and Cancel a date gives a whole day off or takes back a few hours: pick the days in the calendar (a click adds or removes a day, shift-click adds a run of days, to set holidays at once), press Continue, then choose the hours. Add weekly hours repeats some hours on chosen weekdays, for good or between two dates (for example Monday to Friday, 18:00–21:00, until the end of June); the same dialog lists your weekly hours to change or remove them, with the length of a session and your time zone. A click on a day shows what it holds, its sessions and its exceptions, which you can remove. Every change is saved at once. Players see the slots all this makes, minus the sessions already booked. Coach profile sets your picture, headline, presentation, events, languages and price; it pauses bookings when you need to, or keeps them to the students you already coached. Dashboard sums up the next four weeks: booked sessions and hours, the income they will bring, the free slots left and the next sessions. Students lists everyone who booked or wrote to you, with your conversation, the sessions you had together and private notes only you can read.</p>
    </>}
    {page === 'methodsGuide' && <MethodsGuide puzzle={puzzle} method={method} />}
    {page === 'notationGuide' && <>
      <p className="text-base text-foreground/80!">Algorithms are written as a list of moves, one letter per face. Choose a move to watch it turn on the cube.</p>
      <NotationContent guide />
    </>}
    {page === 'averagesGuide' && <>
      <p className="text-base text-foreground/80!">A single best shows what happened once. An average shows how you usually solve. Here is how the <a href="/">Cubix timer</a> calculates them.</p>
      <h2>Average of 5 (Ao5)</h2><p>Take five consecutive results, drop the fastest and the slowest, average the remaining three. For 10.00, 12.00, 13.00, 14.00 and 20.00: (12 + 13 + 14) ÷ 3 = <strong>13.00</strong>.</p>
      <h2>Average of 12 (Ao12)</h2><p>Same idea with twelve results: drop the best and worst, average the ten left. Twelve solves from 10 to 21 seconds give an Ao12 of <strong>15.50</strong>.</p>
      <h2>+2 and DNF</h2><p>A +2 adds two seconds before sorting. A DNF counts as the worst result. One DNF is dropped as the worst; two or more make the average DNF.</p>
      <h2>Best and mean</h2><p>Best is the fastest valid result. Mean averages all valid results without dropping any. Ao5 and Ao12 use the most recent five or twelve results and stay blank until enough solves exist.</p>
      <h2>Personal bests</h2><p>A timer solve that beats your all-time best single, Ao5 or Ao12 for the puzzle, scramble type and solve mode shows a brief green message. The first result sets the record without beating one.</p>
      <p>Official rules: <a href="https://www.worldcubeassociation.org/regulations/#9b">WCA formats</a> and <a href="https://www.worldcubeassociation.org/regulations/#9f">results</a>.</p>
    </>}
    <nav className="mt-10 flex flex-wrap gap-x-4 gap-y-1 border-t pt-4 text-xs [&_a]:font-normal [&_a]:text-muted-foreground" aria-label="Guides"><a href="/">Timer</a><a href="/algorithms/">Algorithms</a><a href="/training/">Trainer</a><a href="/guides/about-cubix/">About</a><a href="/guides/cube-algorithms/">Algorithm guide</a><a href="/guides/algorithm-training/">Training guide</a><a href="/guides/how-to-use-a-cube-timer/">Timer guide</a><a href="/guides/cube-duel/">Duel guide</a><a href="/guides/cubing-coaching/">Coaching guide</a><a href="/guides/solving-methods/">Solving methods</a><a href="/guides/cube-notation/">Notation</a><a href="/guides/ao5-ao12/">Ao5 &amp; Ao12</a></nav>
    <footer className="mt-3 text-xs [&_p]:text-xs"><p>Cubix is an independent speedcubing app. Rubik’s is a trademark of its respective owner. <a href="https://github.com/Vitrixxl/cubix">Source code</a></p></footer>
  </section>;
}
