import type { PuzzleId } from '../../src/shared/puzzles';
import { MethodsGuide } from './Methods';
import { NotationContent } from '../renderer/notation';
import { GUIDES, type Guide } from './pages';
import { tr } from "../../src/client/i18n";
import { said } from "../renderer/base";

/**
 * A guide's text: its sections' headings, muted paragraphs and lists, links in the accent, folded questions; the
 * first paragraph, the lead, a step larger and brighter.
 */
const PROSE =
  "flex max-w-2xl flex-col text-sm leading-relaxed [&_h2]:mt-8 [&_h2]:mb-2 [&_h2]:text-base [&_h2]:font-semibold [&_h2]:tracking-tight [&_h2]:text-foreground [&_p]:mb-3 [&_p]:text-muted-foreground [&_li]:text-muted-foreground [&_strong]:font-medium [&_strong]:text-foreground [&_a]:font-medium [&_a]:text-primary [&_a]:underline-offset-4 [&_a:hover]:underline [&_ol]:mb-3 [&_ol]:flex [&_ol]:list-decimal [&_ol]:flex-col [&_ol]:gap-2 [&_ol]:pl-5 [&_details]:border-b [&_details]:py-3 [&_summary]:cursor-pointer [&_summary]:font-medium [&_summary]:text-foreground [&_details_p]:mt-2 [&_details_p]:mb-0 [&>p:first-of-type]:text-base [&>p:first-of-type]:text-foreground/80";

export function GuideContent({ page, puzzle = '333', method = '' }: { page: Guide; puzzle?: PuzzleId; method?: string }) {
  return <section className={PROSE} aria-label={tr("About Cubix")}>
    <header className="mb-4"><h1 className="text-2xl font-semibold tracking-tight text-balance">{said(GUIDES[page].heading)}</h1></header>
    {page === 'overviewGuide' && <>
      <p>{tr("Cubix is a free cube timer and algorithm trainer for desktop and mobile. Sign in and tell Cubix the puzzles you can solve to start.")}</p>
      <div className="mt-4 grid gap-x-8 gap-y-2 sm:grid-cols-2 [&_h2]:mt-2 [&_p_a]:mr-3">
        <section><h2>{tr("Timer")}</h2><p>{tr("Apply the scramble, hold Space (or touch the screen), release to start, press any key to stop. Times, Ao5 and Ao12 are kept per puzzle.")}</p><p><a href="/guides/how-to-use-a-cube-timer/">{tr("Timer guide")}</a><a href="/guides/cube-duel/">{tr("Duel guide")}</a><a href="/guides/cubing-coaching/">{tr("Coaching guide")}</a></p></section>
        <section><h2>{tr("Algorithms")}</h2><p>{tr("F2L, OLL and PLL cases with diagrams, setups and algorithms from trusted sources. 2×2 to 7×7, Square-1, Pyraminx, Skewb, Megaminx and Clock are included.")}</p><p><a href="/guides/cube-algorithms/">{tr("Algorithm guide")}</a></p></section>
        <section><h2>{tr("Training")}</h2><p>{tr("Pick the cases you want to drill. Cubix shows a setup, times your execution and tracks your progress per case.")}</p><p><a href="/guides/algorithm-training/">{tr("Training guide")}</a></p></section>
        <section><h2>{tr("Averages")}</h2><p>{tr("Best, mean, Ao5 and Ao12 with +2 and DNF handled the WCA way.")}</p><p><a href="/guides/ao5-ao12/">{tr("Ao5 and Ao12 explained")}</a></p></section>
      </div>
      <h2>{tr("Learning a new puzzle")}</h2>
      <p>{tr("Picking a puzzle opens its timer. A puzzle you cannot solve yet opens on its course in Learn instead, and asks whether you want to learn it: Start learning opens the recommended method, Unlock everything opens the puzzle everywhere, and Not now goes back to the previous puzzle. Until its course is finished, Timer, Algorithms, Training and Duel are greyed for that puzzle; clicking one offers to skip the tutorial, which opens them at once. Finishing a course with Finish does the same.")}</p>
      <h2>{tr("Assisted solve (3×3 beginner)")}</h2>
      <p>{tr("In the 3×3 beginner course, Assisted solve solves your own cube with you. Show its six faces to the camera as each instruction says, then check the colours on the net: pick a colour and click a sticker read wrong. Hold the cube yellow on top and green in front all the way through: each step of the course shows its turns, piece by piece, on a 3D copy of your cube. Press Next turn (or the right arrow) after each turn, Back to undo one. Lost? Read the cube again: the solve starts over from where your cube stands, the steps already done are kept.")}</p>
      <h2>{tr("Your account page")}</h2>
      <p>{tr("Change the puzzles you can solve, and the methods you use on each, with Redo the introduction in the guides; Replay tour replays the guided visit.")}</p>
      <p>{tr("The Account tab is your dashboard. Overview shows four cards for the selected puzzle and solve mode: your best time with Ao5 and Ao12, the cases you have trained and learned, your unlocked achievements with the next goal, and your active days. Click a card to open its section.")}</p>
      <p>{tr("Timer lists best, mean, Ao5 and Ao12 for one puzzle, scramble type and solve mode, with a chart of every solve and the rolling Ao5; hover the chart to read a solve, click a row to edit it. Training shows each case with its best attempt; open one for its own chart. Achievements groups goals per puzzle. Settings holds the theme, the accent colour and sign-out.")}</p>
      <h2>{tr("Questions")}</h2>
      <details><summary>{tr("Is Cubix free? Do I need an account?")}</summary><p>{tr("Yes, it is free, with a free account: your practice is saved on your device first, then synchronised between your devices with achievements that follow you everywhere.")}</p></details>
      <details><summary>{tr("Does it work offline?")}</summary><p>{tr("Once installed, the app works without a connection. Sync needs a connection.")}</p></details>
      <details><summary>{tr("Does it work on a phone?")}</summary><p>{tr("Yes. Hold a free area of the screen to arm the timer, release to start, tap to stop.")}</p></details>
      <details><summary>{tr("Is this an official competition timer?")}</summary><p>{tr("No. Cubix is a practice tool and is not affiliated with Rubik’s or the World Cube Association.")}</p></details>
    </>}
    {page === 'algorithmsGuide' && <>
      <p>{tr("The library lists every case with its diagram, setup and algorithms. Open a case to compare its algorithms and see your statistics.")}</p>
      <h2>{tr("3D case player")}</h2><p>{tr("The cube of a case shows the case, then plays its algorithm move by move: play or pause, step one move back or forward, restart, change the speed, or drag the bar under it to any point. The move being played is lit in the algorithm; click a move to turn it, click another algorithm to play that one, and press Replay to watch again from the case. Space plays or pauses and the arrow keys step while the player has the focus. Drag the cube to see it from another angle and double-click it to come back. Blue is the front reference and red is the right reference. OLL highlights orientation, PLL highlights the last layer, and F2L hides last-layer pieces. Notation, in the toolbar, explains every move letter on the cube.")}</p>
      <h2>{tr("Browse by stage")}</h2><p>{tr("F2L pairs a corner and an edge to finish the first two layers. OLL orients the last layer. PLL permutes it. ZBLL finishes the last layer in one algorithm when its edges are already oriented, sorted by corner pattern (T, U, L, Pi, H, S, AS). Use the stage tabs to jump between them and the set switches to choose 2-look or full variants.")}</p>
      <h2>{tr("Solving methods")}</h2><p>{tr("Methods in the toolbar opens a short explanation of each way to solve the selected puzzle, such as CFOP, Roux or ZZ on the 3×3. See")}{" "}<a href="/guides/solving-methods/">{tr("Solving methods")}</a><a href="/guides/cube-notation/">{tr("Notation")}</a>.</p>
      <h2>{tr("From reference to practice")}</h2><p>{tr("Press Train on a case or Train all on a group to open the")}{" "}<a href="/training/">{tr("trainer")}</a> {" "}{tr("with that selection. Trained cases show their best and mean time on their card.")}</p>
      <p>{tr("Sources are shown next to each algorithm. The")}{" "}<a href="https://github.com/Vitrixxl/cubix">{tr("Cubix source repository")}</a> {" "}{tr("documents the catalogue.")}</p>
    </>}
    {page === 'trainingGuide' && <>
      <p>{tr("The trainer repeats the cases you choose so you can work on recognition and execution separately from full solves.")}</p>
      <h2>{tr("Choose what to train")}</h2><p>{tr("Training opens on its setup screen: the modes are listed on the left and the chosen one is described on the right with its Start button. The back arrow in the header of a running training returns to this screen; your selection and settings are kept.")}</p>
      <h2>{tr("Cross + 1 (3×3)")}</h2><p>{tr("Cross + 1 trains the first block. After scrambling, turn the cube over with z2 so white is on the bottom and green stays in front. The block is a back F2L pair (BR or BL) with its two cross edges, a 2×2×2. Choose 3, 4 or 5 moves; every scramble is a random cube whose shortest back block takes exactly that number of face turns, the other cross edges being anywhere. Build the block, finish the cross and the pair if you like, then stop the timer. Show solution lists optimal ways to build the block in that orientation and which block each one builds. The number of moves can be changed in the header; times are kept per move count and appear in Account → Timer under their own scramble type.")}</p>
      <h2>{tr("Review everything learned")}</h2><p>{tr("Choose Review learned on the setup screen to mix every case marked learned for the selected puzzle, across all stages and sets. Each timed attempt or Next picks another case. New learned cases join automatically; removing a learned mark removes the case from review after the current attempt. Daily assignments and your free-practice selection are preserved.")}</p>
      <h2>{tr("Daily learning (3×3)")}</h2><p>{tr("Choose Learn F2L, Learn OLL or Learn PLL on the 3×3 setup screen. Repeat the algorithm of the day as often as you like, then mark it learned. It stays assigned across restarts and missed days until learned; the next case arrives on the following local calendar day. You can keep practising today’s case after learning it, or undo Learned. Open Groups and use the up and down arrows to choose the order of case families. The order is saved per track on this device. Reordering keeps today’s case and affects future assignments; already learned cases are skipped. Each track remembers its own case. Press Train learned to repeat every case of the track you have already marked learned, one random case per attempt; press it again to return to today’s case. Free practice restores your manual selection. Daily assignments stay on this device for each account; learned marks synchronise with your account.")}</p>
      <h2>{tr("Set up a session")}</h2><ol><li>{tr("Choose Free practice, select the cases to practise (a whole set, a group or single cases) and press Start.")}</li><li>{tr("Apply the setup shown on your cube.")}</li><li>{tr("Hold Space (or a free area of the screen), release to start, press any key to stop.")}</li><li>{tr("Review the session in Times. Undo removes the last time.")}</li></ol>
      <h2>{tr("Tips")}</h2><p>{tr("Start with a few cases you confuse. Keep the solution hidden to train recognition, reveal it when needed. Random U turns before the setup make recognition harder, as in a real solve.")}</p>
      <p>{tr("For full solves, open the")}{" "}<a href="/">{tr("timer")}</a>{tr(". The")}{" "}<a href="/guides/ao5-ao12/">{tr("averages guide")}</a> {" "}{tr("explains the statistics.")}</p>
    </>}
    {page === 'timerGuide' && <>
      <p>{tr("Cubix times physical solves with your keyboard or touchscreen.")}{" "}<a href="/">{tr("Open the timer")}</a> {" "}{tr("and follow these steps.")}</p>
      <h2>{tr("1. Choose a puzzle and scramble")}</h2><p>{tr("The puzzle selector at the top of the sidebar changes the puzzle everywhere. The scramble type, solve mode and entry are chosen in the page header, next to Replay and New scramble. Normal generates a scramble for the selected WCA event. The session figures run along the bottom: best in green, worst in red, the current Ao5 and Ao12 in the accent colour, with their best values beside them.")}</p>
      <p>{tr("The 3D cube plays the complete scramble in three seconds for 2×2 and 3×3 cubes. Each larger size adds one second, from four seconds for 4×4 to seven seconds for 7×7. Drag it to change the viewing angle or use Replay to watch the scramble again. Long scrambles scroll inside their text area while the cube and timer remain visible.")}</p>
      <h2>{tr("2. Start")}</h2><p>{tr("Hold Space for 0.3 seconds until the time turns green, then release. Releasing early cancels. On a phone, hold a free area of the screen and release when ready.")}</p>
      <h2>{tr("3. Stop and review")}</h2><p>{tr("Press any key or tap the screen to stop. The time is saved and the next scramble appears. Buttons under the time let you add a +2, mark it DNF, write a comment or delete it. Each time in the Times list has the same +2, DNF and delete buttons, and its i button opens the solve with its scramble and comment.")}</p>
      <h2>{tr("Typing and casual entry")}</h2><p>{tr("The entry menu next to the scramble type chooses how times come in. Timer is the built-in timer. Typing replaces it with a field for a time measured on an external timer such as a speed-stacking mat: type it and press Enter. Bare digits are read from the right, so 1234 is 12.34 and 12345 is 1:23.45; 12.34 and 1:23.45 work too. Casual runs the timer without recording anything: the time is shown, then forgotten, and the session, statistics and profile stay untouched.")}</p>
      <h2>{tr("Explore your progress")}</h2><p>{tr("In Account → Timer, the chart sits above your times. Scroll over the chart to zoom around the pointer, or drag across it to select a period. Hold Shift while dragging to move through the history; horizontal trackpad scrolling also moves the visible period. Dates along the bottom show the visible period and the list below follows it. Hover to read a single time and its rolling Ao5. Double-click the chart or use Reset zoom inside it to return to the full history. With the chart focused, use + and − to zoom, the arrow keys to move, Home to reset, and Escape to cancel a selection. The summary cards always describe the full history for the selected puzzle and mode.")}</p>
      <h2>{tr("Modes")}</h2><p>{tr("Standard, one-handed and blindfolded keep separate histories. Blindfolded time includes memorisation. Times are saved on your device first, then synchronised with your account.")}</p>
      <p>{tr("For official competitions, follow the")}{" "}<a href="https://www.worldcubeassociation.org/regulations/">{tr("WCA Regulations")}</a>.</p>
    </>}
    {page === 'smartCubeGuide' && <>
      <p>{tr("A connected cube tells Cubix every turn you make. On the 3×3 timer and in the trainer it starts and stops the timer by itself, and every solve it records is analysed step by step. Connect it with the cube button in the header of the timer or of a running training.")}</p>
      <h2>{tr("Timed solves")}</h2><p>{tr("The scramble colours its turns as you make them; a wrong turn shows the turns that undo it. Once the cube is scrambled, your first turn starts the timer and the solved cube stops it, with the cube’s own clock. Stopping with a key before the cube is solved gives a +2 when one face turn is left, a DNF otherwise. The turns are saved with the solve: every list marks these solves with a small 3D cube, and opening one replays it and shows its analysis.")}</p>
      <h2>{tr("Analysis")}</h2><p>{tr("Account → Analysis gathers every solve done on a connected cube; it stays empty until you have one. Each solve is split into the cross, the four F2L pairs, the OLL and the PLL, and each step’s time into recognition (the pause before its first turn) and execution. The method buttons show every solve together, or only the solves of one method: CFOP with a one-look last layer, CFOP with the last layer in two looks, or CFOP finished with a ZBLL. Steps lists each step’s mean time, its part of the solve, its turns, its turns per second while turning and how often it was skipped. Cases lists every case of the catalogue met in your solves, the slowest first; click one to open it, or train it from its row.")}</p>
      <h2>{tr("Suggested training")}</h2><p>{tr("From your solves Cubix suggests what to train: your slowest F2L pairs, OLLs and PLLs, the last-layer cases you take longest to recognise, Cross + 1 when your cross is long, or the full OLL or PLL when you solve the last layer in two looks. Train starts it on the 3×3.")}</p>
      <h2>{tr("Case times in the algorithm library")}</h2><p>{tr("A case done during a solve on a connected cube counts as an attempt of that case, timed from the end of the step before to its last turn. In a case’s statistics, All shows these attempts with the trainer’s, In solves only the ones from solves (marked In solve; a click opens the solve), and Training only the trainer’s. The best time on each case’s card follows the same choice.")}</p>
      <h2>{tr("Training on the cube")}</h2><p>{tr("In a 3×3 training of F2L, OLL, PLL or ZBLL cases, the setup is shown as the face turns to make on the cube and lights up as you make them from a solved cube. Cubix sees the case once it is set up, whatever the angle; your first turn starts the timer, turns of the top alone excepted, and the case solved stops it: the first two layers for an F2L case, the oriented top for an OLL, the solved cube, a turn of the top away, for a PLL or a ZBLL. An OLL can be set up straight from the end of the previous one; an F2L case needs the other pairs and the cross solved, a PLL the rest of the cube.")}</p>
      <p>{tr("Bluetooth cubes will connect as their drivers arrive; until then the development version plays a virtual cube.")}</p>
    </>}
    {page === 'communityGuide' && <>
      <p>{tr("Messages (Alt+7) is where you meet other players: your conversations with friends and groups, the battles and tournaments launched in them. Tournaments (Alt+6) lists every tournament you can play. Both need an account.")}</p>
      <h2>{tr("Friends")}</h2><p>{tr("Friends, at the top of Messages, finds a player by the start of their username: Add sends them a request. It also gives your link: whoever opens it is asked to add you, even if they create their account for it. The bell counts what waits for an answer: the friend requests you received, the group invitations, and the requests you sent, which you can take back. Friends can write to each other; removing a friend keeps the conversation but closes it.")}</p>
      <h2>{tr("Conversations")}</h2><p>{tr("Your conversations with friends and with groups are one list, the latest first, with the invitations to groups on top. Enter sends, Shift+Enter starts a new line. A message arriving while you are elsewhere shows a notice, and Messages in the sidebar counts what you have not read yet, with what waits for an answer. The button on the right of a conversation opens its details: a friend's battles with you and your record, or a group's members, tournaments and battles.")}</p>
      <h2>{tr("Groups")}</h2><p>{tr("New group creates a group with the friends you tick, who are invited at once. Its owner and the admins the owner names invite and remove members and organise its tournaments; every member talks in it and launches battles. The owner deletes the group; the others leave it from its details.")}</p>
      <h2>{tr("Battles")}</h2><p>{tr("Battle, at the top of a conversation, challenges your friend, or in a group one member or anyone in it, with the event and the format you choose. The battle shows in the conversation as a card that follows it live: accept it, play it, or open it to see every solve, both times and its scramble. Either player can call it off before it starts.")}</p>
      <h2>{tr("Matches")}</h2><p>{tr("Tournament matches and battles are races of sets: both players solve the same scramble, the faster takes the solve, a DNF loses to any time and a tie gives nothing. The first to the number of solves chosen takes the set, the first to the number of sets chosen takes the match. The match waits until both players have its page open; hold Space as on the timer, and correct your latest solve with +2, DNF or Redo while your opponent has not solved it. After each solve the page says who took it and by how much, and a won set is announced. Forfeit gives the match away.")}</p>
      <h2>{tr("Tournaments")}</h2><p>{tr("A tournament is a knockout bracket. Register before its date; at its date registration closes and the players are drawn into the bracket, the first drawn going straight through when the count is not a power of two. A round opens only once every match of the round before is over: everyone waits for everyone. The bracket shows each match as it stands, live, over or waiting, and Play takes you to yours. The tournaments open to every player are created by the Qbix team; a group's are created by its owner and admins from the top of its conversation, where its card lets members register. They can also start it early, cancel it, or give a match to a player whose opponent never came.")}</p>
    </>}
    {page === 'duelGuide' && <>
      <p>{tr("Duel races you against another cuber, live, on the same scrambles. Open it from the crossed swords in the sidebar (Alt+5).")}</p>
      <h2>{tr("1. Find an opponent")}</h2><p>{tr("Choose the puzzle in the sidebar, then Find an opponent. There is no rating: your level is the mean of your last twelve timer solves on that puzzle, without the best and the worst, once five of them count. You meet the player searching the same puzzle whose level is closest to yours. The range accepted widens the longer you wait, from 15% at once to anyone after 30 seconds, so a quiet moment still gives you a race. Without a level you first meet other new players, then anyone after 10 seconds. Players race under their username.")}</p>
      <h2>{tr("2. Race five rounds")}</h2><p>{tr("Both of you get the same five scrambles, one round at a time. Your timer is on the left, your opponent's on the right, with the scrambled cube between them: drag it to turn it, or hide it with its × or the Cube cell of the header. Start and stop like on the timer page. You see your opponent hold, start and stop as it happens, and the next round opens once you have both finished.")}</p>
      <h2>{tr("3. +2, DNF and Cancel")}</h2><p>{tr("The cells at the end of your row put a +2 or a DNF on your latest solve, or take it off again. Cancel takes your solve back so you can redo it on the same scramble, as long as your opponent has not finished that round.")}</p>
      <h2>{tr("4. The result")}</h2><p>{tr("After five rounds the best Ao5 wins: best and worst dropped, one DNF counts as the worst, two make the average DNF. The result dialog offers a rematch, which starts once you both accept it on five new scrambles, or a new opponent. Your recent battles appear in Account.")}</p>
      <h2>{tr("Chat")}</h2><p>{tr("The chat runs beside the race on wide screens and behind the Chat cell otherwise. Messages last as long as the race.")}</p>
    </>}
    {page === 'coachingGuide' && <>
      <p>{tr("Coaching puts you in a video call with a cuber who teaches. Open it from the headset in the sidebar (Alt+8).")}</p>
      <h2>{tr("1. Find a coach")}</h2><p>{tr("Find a coach lists every coach with their rating, the events they teach, their best times, their price per session and their next free slot. Search by name, language or method, or keep one event. A coach's page shows who they are, what their students wrote about them and the share of each rating.")}</p>
      <h2>{tr("2. Book a session")}</h2><p>{tr("A coach's page opens on booking, in three numbered steps. The calendar shows the coach's free slots over the next four weeks, month by month and in your own time zone: click a time in a day to pick it, or the day to see all its times. Pick a day, then a time, say what you want to work on and Book: the session is confirmed at once. Payment is not asked for yet. Slots start an hour from now at the earliest.")}</p>
      <h2>{tr("3. Talk with your coach")}</h2><p>{tr("Booking opens a conversation with the coach, and Message on a coach's page opens one before booking. Messages arrive live; the sidebar counts the unread ones and a notice offers to open them from any page. To show your solves, send pictures (up to 10 MB) or videos (up to 64 MB): pick them with the clip beside the message box, paste them, or drop them on the conversation. Only you and the other party can open them.")}</p>
      <h2>{tr("4. The call")}</h2><p>{tr("Sessions lists what is coming. Join call opens a quarter of an hour before the session and stays open half an hour after it; when the other party is already in, you are told on any page. The browser asks once for the camera and the microphone. In the call you can mute, turn the camera off, share your screen to show an algorithm sheet, and keep the chat beside the video. Cancel a session from its row: the other party is told and the slot opens again.")}</p>
      <h2>{tr("5. Review")}</h2><p>{tr("Once a session is over, Review gives the coach one to five stars and a few words. You can change your review later; it appears on the coach's page under your username.")}</p>
      <h2>{tr("Becoming a coach")}</h2><p>{tr("Become a coach sends the team your e-mail address, the events you would teach, your level and how you would coach. The team answers by e-mail. Once you are accepted, the Coaching section gains your Dashboard, Students, Schedule and Coach profile.")}</p>
      <h2>{tr("For coaches")}</h2><p>{tr("Schedule shows your month as a calendar, on your own clock, with the sessions booked in it: click one to see who booked, their practice and your notes, and open their whole profile. Edit availability asks what you want to change. Add a date opens hours on days you are usually closed, and Cancel a date gives a whole day off or takes back a few hours: pick the days in the calendar (a click adds or removes a day, shift-click adds a run of days, to set holidays at once), press Continue, then choose the hours. Add weekly hours repeats some hours on chosen weekdays, for good or between two dates (for example Monday to Friday, 18:00–21:00, until the end of June); the same dialog lists your weekly hours to change or remove them, with the length of a session and your time zone. A click on a day shows what it holds, its sessions and its exceptions, which you can remove. Every change is saved at once. Players see the slots all this makes, minus the sessions already booked. Coach profile sets your picture, headline, presentation, events, languages and price; it pauses bookings when you need to, or keeps them to the students you already coached. Dashboard sums up the next four weeks: booked sessions and hours, the income they will bring, the free slots left and the next sessions. Students lists everyone who booked or wrote to you, with your conversation, the sessions you had together and private notes only you can read.")}</p>
    </>}
    {page === 'methodsGuide' && <MethodsGuide puzzle={puzzle} method={method} />}
    {page === 'notationGuide' && <>
      <p>{tr("Algorithms are written as a list of moves, one letter per face. Choose a move to watch it turn on the cube.")}</p>
      <NotationContent guide />
    </>}
    {page === 'averagesGuide' && <>
      <p>{tr("A single best shows what happened once. An average shows how you usually solve. Here is how the")}{" "}<a href="/">{tr("Cubix timer")}</a> {" "}{tr("calculates them.")}</p>
      <h2>{tr("Average of 5 (Ao5)")}</h2><p>{tr("Take five consecutive results, drop the fastest and the slowest, average the remaining three. For 10.00, 12.00, 13.00, 14.00 and 20.00: (12 + 13 + 14) ÷ 3 =")}{" "}<strong>13.00</strong>.</p>
      <h2>{tr("Average of 12 (Ao12)")}</h2><p>{tr("Same idea with twelve results: drop the best and worst, average the ten left. Twelve solves from 10 to 21 seconds give an Ao12 of")}{" "}<strong>15.50</strong>.</p>
      <h2>{tr("+2 and DNF")}</h2><p>{tr("A +2 adds two seconds before sorting. A DNF counts as the worst result. One DNF is dropped as the worst; two or more make the average DNF.")}</p>
      <h2>{tr("Best and mean")}</h2><p>{tr("Best is the fastest valid result. Mean averages all valid results without dropping any. Ao5 and Ao12 use the most recent five or twelve results and stay blank until enough solves exist.")}</p>
      <h2>{tr("Personal bests")}</h2><p>{tr("A timer solve that beats your all-time best single, Ao5 or Ao12 for the puzzle, scramble type and solve mode shows a brief green message. The first result sets the record without beating one.")}</p>
      <p>{tr("Official rules:")}{" "}<a href="https://www.worldcubeassociation.org/regulations/#9b">{tr("WCA formats")}</a> {" "}{tr("and")}{" "}<a href="https://www.worldcubeassociation.org/regulations/#9f">{tr("results")}</a>.</p>
    </>}
    <nav className="mt-10 flex flex-wrap gap-x-4 gap-y-1 border-t pt-4 text-xs [&_a]:font-normal [&_a]:text-muted-foreground" aria-label={tr("Guides")}><a href="/">{tr("Timer")}</a><a href="/algorithms/">{tr("Algorithms")}</a><a href="/training/">{tr("Trainer")}</a><a href="/guides/about-cubix/">{tr("About")}</a><a href="/guides/cube-algorithms/">{tr("Algorithm guide")}</a><a href="/guides/algorithm-training/">{tr("Training guide")}</a><a href="/guides/how-to-use-a-cube-timer/">{tr("Timer guide")}</a><a href="/guides/cube-duel/">{tr("Duel guide")}</a><a href="/guides/cubing-coaching/">{tr("Coaching guide")}</a><a href="/guides/solving-methods/">{tr("Solving methods")}</a><a href="/guides/cube-notation/">{tr("Notation")}</a><a href="/guides/ao5-ao12/">{tr("Ao5 &amp; Ao12")}</a></nav>
    <footer className="mt-3 text-xs [&_p]:text-xs"><p>{tr("Cubix is an independent speedcubing app. Rubik’s is a trademark of its respective owner.")}{" "}<a href="https://github.com/Vitrixxl/cubix">{tr("Source code")}</a></p></footer>
  </section>;
}
